### ISSUE TITLE
Game doesn't results in "Win" even after the key is found.

### ISSUE THREAD

**Issue by JOSBEAK** [CeNiEi/YetAnotherDungeonCrawler#1]
As per the game rules the Player must win after the Key is picked , but the game freezes and Key is shown in the item list.

As per my understanding and after going through the source code, it seems that the item component is being wrongly attached to the key.

**Comment by CeNiEi** [comment]
It seems to be the case.. 
Feel free to open a PR with the correct changes, if you want.
